# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2571704b484f447075d7b5eb71381cd0b54b5aa9b71a0e0b47f91678f1cc453bfea753e7fc8daacbc53f4f19342d64bf29779171cf73e5259aa662477bc4b7aa

test:
  secret_key_base: 278ee61a591e692ce1d68dfcf8fbcc36ed2c01a42177afd4e864f6947fefa5f197a18c62dbda70a1206270f84ae89775f56ad6fb3474e24b21a5cb97d0bd1440

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
